#!/bin/bash

changeupper < $1 > $2

if [ "$#" -gt 2 ]; then
   echo "Too many arguments entered. To use: lc file1 file2. This program lowercases all letters in file1 and writes file2."
fi

if [ "$#" -lt 2 ]; then
   echo "Too few arguments entered. To use: lc file1 file2. This program lowercases all letter in file1 and writes file2."
fi
